import db, { Currency } from "../";

const currencies = [
  {
    id: 1,
    symbol: "AED",
    name: "United Arab Emirates Dirham",
    symbol_native: "د.إ",
    decimal_digits: 2,
    rounding: 0,
    code: "AED",
    name_plural: "UAE dirhams",
    type: "fiat",
  },
  {
    id: 2,
    symbol: "Af",
    name: "Afghan Afghani",
    symbol_native: "؋",
    decimal_digits: 0,
    rounding: 0,
    code: "AFN",
    name_plural: "Afghan Afghanis",
    type: "fiat",
  },
  {
    id: 3,
    symbol: "ALL",
    name: "Albanian Lek",
    symbol_native: "Lek",
    decimal_digits: 0,
    rounding: 0,
    code: "ALL",
    name_plural: "Albanian lekë",
    type: "fiat",
  },
  {
    id: 4,
    symbol: "AMD",
    name: "Armenian Dram",
    symbol_native: "դր.",
    decimal_digits: 0,
    rounding: 0,
    code: "AMD",
    name_plural: "Armenian drams",
    type: "fiat",
  },
  {
    id: 5,
    symbol: "ƒ",
    name: "NL Antillean Guilder",
    symbol_native: "NAƒ",
    decimal_digits: 2,
    rounding: 0,
    code: "ANG",
    icon_name: "ang",
    name_plural: "NL Antillean Guilders",
    type: "fiat",
  },
  {
    id: 6,
    symbol: "Kz",
    name: "Angolan Kwanza",
    symbol_native: "Kz",
    decimal_digits: 2,
    rounding: 0,
    code: "AOA",
    icon_name: "aoa",
    name_plural: "Angolan Kwanza",
    type: "fiat",
  },
  {
    id: 7,
    symbol: "AR$",
    name: "Argentine Peso",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "ARS",
    name_plural: "Argentine pesos",
    type: "fiat",
  },
  {
    id: 8,
    symbol: "AU$",
    name: "Australian Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "AUD",
    name_plural: "Australian dollars",
    type: "fiat",
  },
  {
    id: 9,
    symbol: "Afl.",
    name: "Aruban Florin",
    symbol_native: "Afl.",
    decimal_digits: 2,
    rounding: 0,
    code: "AWG",
    icon_name: "awg",
    name_plural: "Aruban Florin",
    type: "fiat",
  },
  {
    id: 10,
    symbol: "man.",
    name: "Azerbaijani Manat",
    symbol_native: "ман.",
    decimal_digits: 2,
    rounding: 0,
    code: "AZN",
    name_plural: "Azerbaijani manats",
    type: "fiat",
  },
  {
    id: 11,
    symbol: "KM",
    name: "Bosnia-Herzegovina Convertible Mark",
    symbol_native: "KM",
    decimal_digits: 2,
    rounding: 0,
    code: "BAM",
    name_plural: "Bosnia-Herzegovina convertible marks",
    type: "fiat",
  },
  {
    id: 12,
    symbol: "Bds$",
    name: "Barbadian Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "BBD",
    icon_name: "bbd",
    name_plural: "Barbadian Dollars",
    type: "fiat",
  },
  {
    id: 13,
    symbol: "Tk",
    name: "Bangladeshi Taka",
    symbol_native: "৳",
    decimal_digits: 2,
    rounding: 0,
    code: "BDT",
    name_plural: "Bangladeshi takas",
    type: "fiat",
  },
  {
    id: 14,
    symbol: "BGN",
    name: "Bulgarian Lev",
    symbol_native: "лв.",
    decimal_digits: 2,
    rounding: 0,
    code: "BGN",
    name_plural: "Bulgarian leva",
    type: "fiat",
  },
  {
    id: 15,
    symbol: "BD",
    name: "Bahraini Dinar",
    symbol_native: "د.ب.‏",
    decimal_digits: 3,
    rounding: 0,
    code: "BHD",
    name_plural: "Bahraini dinars",
    type: "fiat",
  },
  {
    id: 16,
    symbol: "FBu",
    name: "Burundian Franc",
    symbol_native: "FBu",
    decimal_digits: 0,
    rounding: 0,
    code: "BIF",
    name_plural: "Burundian francs",
    type: "fiat",
  },
  {
    id: 17,
    symbol: "BD$",
    name: "Bermudan Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "BMD",
    icon_name: "bmd",
    name_plural: "Bermudan Dollars",
    type: "fiat",
  },
  {
    id: 18,
    symbol: "BN$",
    name: "Brunei Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "BND",
    name_plural: "Brunei dollars",
    type: "fiat",
  },
  {
    id: 19,
    symbol: "Bs",
    name: "Bolivian Boliviano",
    symbol_native: "Bs",
    decimal_digits: 2,
    rounding: 0,
    code: "BOB",
    name_plural: "Bolivian bolivianos",
    type: "fiat",
  },
  {
    id: 20,
    symbol: "R$",
    name: "Brazilian Real",
    symbol_native: "R$",
    decimal_digits: 2,
    rounding: 0,
    code: "BRL",
    name_plural: "Brazilian reals",
    type: "fiat",
  },
  {
    id: 21,
    symbol: "B$",
    name: "Bahamian Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "BSD",
    icon_name: "bsd",
    name_plural: "Bahamian Dollars",
    type: "fiat",
  },
  {
    id: 22,
    symbol: "Nu.",
    name: "Bhutanese Ngultrum",
    symbol_native: "Nu.",
    decimal_digits: 2,
    rounding: 0,
    code: "BTN",
    icon_name: "btn",
    name_plural: "Bhutanese Ngultrum",
    type: "fiat",
  },
  {
    id: 23,
    symbol: "BWP",
    name: "Botswanan Pula",
    symbol_native: "P",
    decimal_digits: 2,
    rounding: 0,
    code: "BWP",
    name_plural: "Botswanan pulas",
    type: "fiat",
  },
  {
    id: 24,
    symbol: "Br",
    name: "Belarusian ruble",
    symbol_native: "Br",
    decimal_digits: 2,
    rounding: 0,
    code: "BYN",
    name_plural: "Belarusian rubles",
    type: "fiat",
  },
  {
    id: 25,
    symbol: "BYR",
    name: "Belarusian Ruble",
    symbol_native: "BYR",
    decimal_digits: 0,
    rounding: 0,
    code: "BYR",
    name_plural: "Belarusian rubles",
    type: "fiat",
  },
  {
    id: 26,
    symbol: "BZ$",
    name: "Belize Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "BZD",
    name_plural: "Belize dollars",
    type: "fiat",
  },
  {
    id: 27,
    symbol: "CA$",
    name: "Canadian Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "CAD",
    name_plural: "Canadian dollars",
    type: "fiat",
  },
  {
    id: 28,
    symbol: "CDF",
    name: "Congolese Franc",
    symbol_native: "FrCD",
    decimal_digits: 2,
    rounding: 0,
    code: "CDF",
    name_plural: "Congolese francs",
    type: "fiat",
  },
  {
    id: 29,
    symbol: "CHF",
    name: "Swiss Franc",
    symbol_native: "CHF",
    decimal_digits: 2,
    rounding: 0,
    code: "CHF",
    name_plural: "Swiss francs",
    type: "fiat",
  },
  {
    id: 30,
    symbol: "UF",
    name: "Unidad de Fomento",
    symbol_native: "UF",
    decimal_digits: 2,
    rounding: 0,
    code: "CLF",
    name_plural: "Unidad de Fomentos",
    type: "fiat",
  },
  {
    id: 31,
    symbol: "CL$",
    name: "Chilean Peso",
    symbol_native: "$",
    decimal_digits: 0,
    rounding: 0,
    code: "CLP",
    name_plural: "Chilean pesos",
    type: "fiat",
  },
  {
    id: 32,
    symbol: "CN¥",
    name: "Chinese Yuan",
    symbol_native: "CN¥",
    decimal_digits: 2,
    rounding: 0,
    code: "CNY",
    name_plural: "Chinese yuan",
    type: "fiat",
  },
  {
    id: 33,
    symbol: "CO$",
    name: "Coombian Peso",
    symbol_native: "$",
    decimal_digits: 0,
    rounding: 0,
    code: "COP",
    name_plural: "Colombian pesos",
    type: "fiat",
  },
  {
    id: 34,
    symbol: "₡",
    name: "Costa Rican Colón",
    symbol_native: "₡",
    decimal_digits: 0,
    rounding: 0,
    code: "CRC",
    name_plural: "Costa Rican colóns",
    type: "fiat",
  },
  {
    id: 35,
    symbol: "CUC$",
    name: "Cuban Convertible Peso",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "CUC",
    icon_name: "cuc",
    name_plural: "Cuban Convertible Peso",
    type: "fiat",
  },
  {
    id: 36,
    symbol: "$MN",
    name: "Cuban Peso",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "CUP",
    icon_name: "cup",
    name_plural: "Cuban Peso",
    type: "fiat",
  },
  {
    id: 37,
    symbol: "CV$",
    name: "Cape Verdean Escudo",
    symbol_native: "CV$",
    decimal_digits: 2,
    rounding: 0,
    code: "CVE",
    name_plural: "Cape Verdean escudos",
    type: "fiat",
  },
  {
    id: 38,
    symbol: "Kč",
    name: "Czech Republic Koruna",
    symbol_native: "Kč",
    decimal_digits: 2,
    rounding: 0,
    code: "CZK",
    name_plural: "Czech Republic korunas",
    type: "fiat",
  },
  {
    id: 39,
    symbol: "Fdj",
    name: "Djiboutian Franc",
    symbol_native: "Fdj",
    decimal_digits: 0,
    rounding: 0,
    code: "DJF",
    name_plural: "Djiboutian francs",
    type: "fiat",
  },
  {
    id: 40,
    symbol: "Dkr",
    name: "Danish Krone",
    symbol_native: "kr",
    decimal_digits: 2,
    rounding: 0,
    code: "DKK",
    name_plural: "Danish kroner",
    type: "fiat",
  },
  {
    id: 41,
    symbol: "RD$",
    name: "Dominican Peso",
    symbol_native: "RD$",
    decimal_digits: 2,
    rounding: 0,
    code: "DOP",
    name_plural: "Dominican pesos",
    type: "fiat",
  },
  {
    id: 42,
    symbol: "DA",
    name: "Algerian Dinar",
    symbol_native: "د.ج.‏",
    decimal_digits: 2,
    rounding: 0,
    code: "DZD",
    name_plural: "Algerian dinars",
    type: "fiat",
  },
  {
    id: 43,
    symbol: "EGP",
    name: "Egyptian Pound",
    symbol_native: "ج.م.‏",
    decimal_digits: 2,
    rounding: 0,
    code: "EGP",
    name_plural: "Egyptian pounds",
    type: "fiat",
  },
  {
    id: 44,
    symbol: "Nfk",
    name: "Eritrean Nakfa",
    symbol_native: "Nfk",
    decimal_digits: 2,
    rounding: 0,
    code: "ERN",
    name_plural: "Eritrean nakfas",
    type: "fiat",
  },
  {
    id: 45,
    symbol: "Br",
    name: "Ethiopian Birr",
    symbol_native: "Br",
    decimal_digits: 2,
    rounding: 0,
    code: "ETB",
    name_plural: "Ethiopian birrs",
    type: "fiat",
  },
  {
    id: 46,
    symbol: "€",
    name: "Euro",
    symbol_native: "€",
    decimal_digits: 2,
    rounding: 0,
    code: "EUR",
    name_plural: "Euros",
    type: "fiat",
  },
  {
    id: 47,
    symbol: "FJ$",
    name: "Fijian Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "FJD",
    icon_name: "fjd",
    name_plural: "Fijian Dollar",
    type: "fiat",
  },
  {
    id: 48,
    symbol: "FK£",
    name: "Falkland Islands Pound",
    symbol_native: "£",
    decimal_digits: 2,
    rounding: 0,
    code: "FKP",
    icon_name: "fkp",
    name_plural: "Falkland Islands Pound",
    type: "fiat",
  },
  {
    id: 49,
    symbol: "£",
    name: "British Pound Sterling",
    symbol_native: "£",
    decimal_digits: 2,
    rounding: 0,
    code: "GBP",
    name_plural: "British pounds sterling",
    type: "fiat",
  },
  {
    id: 50,
    symbol: "GEL",
    name: "Georgian Lari",
    symbol_native: "GEL",
    decimal_digits: 2,
    rounding: 0,
    code: "GEL",
    name_plural: "Georgian laris",
    type: "fiat",
  },
  {
    id: 51,
    symbol: "£",
    name: "Guernsey pound",
    symbol_native: "£",
    decimal_digits: 2,
    rounding: 0,
    code: "GGP",
    name_plural: "Guernsey pounds",
    type: "fiat",
  },
  {
    id: 52,
    symbol: "GH₵",
    name: "Ghanaian Cedi",
    symbol_native: "GH₵",
    decimal_digits: 2,
    rounding: 0,
    code: "GHS",
    name_plural: "Ghanaian cedis",
    type: "fiat",
  },
  {
    id: 53,
    symbol: "£",
    name: "Gibraltar Pound",
    symbol_native: "£",
    decimal_digits: 2,
    rounding: 0,
    code: "GIP",
    icon_name: "gip",
    name_plural: "Gibraltar Pounds",
    type: "fiat",
  },
  {
    id: 54,
    symbol: "D",
    name: "Gambian Dalasi",
    symbol_native: "D",
    decimal_digits: 2,
    rounding: 0,
    code: "GMD",
    icon_name: "gmd",
    name_plural: "Gambian Dalasi",
    type: "fiat",
  },
  {
    id: 55,
    symbol: "FG",
    name: "Guinean Franc",
    symbol_native: "FG",
    decimal_digits: 0,
    rounding: 0,
    code: "GNF",
    name_plural: "Guinean francs",
    type: "fiat",
  },
  {
    id: 56,
    symbol: "GTQ",
    name: "Guatemalan Quetzal",
    symbol_native: "Q",
    decimal_digits: 2,
    rounding: 0,
    code: "GTQ",
    name_plural: "Guatemalan quetzals",
    type: "fiat",
  },
  {
    id: 57,
    symbol: "G$",
    name: "Guyanaese Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "GYD",
    icon_name: "gyd",
    name_plural: "Guyanaese Dollar",
    type: "fiat",
  },
  {
    id: 58,
    symbol: "HK$",
    name: "Hong Kong Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "HKD",
    name_plural: "Hong Kong dollars",
    type: "fiat",
  },
  {
    id: 59,
    symbol: "HNL",
    name: "Honduran Lempira",
    symbol_native: "L",
    decimal_digits: 2,
    rounding: 0,
    code: "HNL",
    name_plural: "Honduran lempiras",
    type: "fiat",
  },
  {
    id: 60,
    symbol: "kn",
    name: "Croatian Kuna",
    symbol_native: "kn",
    decimal_digits: 2,
    rounding: 0,
    code: "HRK",
    name_plural: "Croatian kunas",
    type: "fiat",
  },
  {
    id: 61,
    symbol: "G",
    name: "Haitian Gourde",
    symbol_native: "G",
    decimal_digits: 2,
    rounding: 0,
    code: "HTG",
    icon_name: "htg",
    name_plural: "Haitian Gourde",
    type: "fiat",
  },
  {
    id: 62,
    symbol: "Ft",
    name: "Hungarian Forint",
    symbol_native: "Ft",
    decimal_digits: 0,
    rounding: 0,
    code: "HUF",
    name_plural: "Hungarian forints",
    type: "fiat",
  },
  {
    id: 63,
    symbol: "Rp",
    name: "Indonesian Rupiah",
    symbol_native: "Rp",
    decimal_digits: 0,
    rounding: 0,
    code: "IDR",
    name_plural: "Indonesian rupiahs",
    type: "fiat",
  },
  {
    id: 64,
    symbol: "₪",
    name: "Israeli New Sheqel",
    symbol_native: "₪",
    decimal_digits: 2,
    rounding: 0,
    code: "ILS",
    name_plural: "Israeli new sheqels",
    type: "fiat",
  },
  {
    id: 65,
    symbol: "£",
    name: "Manx pound",
    symbol_native: "£",
    decimal_digits: 2,
    rounding: 0,
    code: "IMP",
    name_plural: "Manx pounds",
    type: "fiat",
  },
  {
    id: 66,
    symbol: "Rs",
    name: "Indian Rupee",
    symbol_native: "টকা",
    decimal_digits: 2,
    rounding: 0,
    code: "INR",
    name_plural: "Indian rupees",
    type: "fiat",
  },
  {
    id: 67,
    symbol: "IQD",
    name: "Iraqi Dinar",
    symbol_native: "د.ع.‏",
    decimal_digits: 0,
    rounding: 0,
    code: "IQD",
    name_plural: "Iraqi dinars",
    type: "fiat",
  },
  {
    id: 68,
    symbol: "IRR",
    name: "Iranian Rial",
    symbol_native: "﷼",
    decimal_digits: 0,
    rounding: 0,
    code: "IRR",
    name_plural: "Iranian rials",
    type: "fiat",
  },
  {
    id: 69,
    symbol: "Ikr",
    name: "Icelandic Króna",
    symbol_native: "kr",
    decimal_digits: 0,
    rounding: 0,
    code: "ISK",
    name_plural: "Icelandic krónur",
    type: "fiat",
  },
  {
    id: 70,
    symbol: "£",
    name: "Jersey pound",
    symbol_native: "£",
    decimal_digits: 2,
    rounding: 0,
    code: "JEP",
    name_plural: "Jersey pound",
    type: "fiat",
  },
  {
    id: 71,
    symbol: "J$",
    name: "Jamaican Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "JMD",
    name_plural: "Jamaican dollars",
    type: "fiat",
  },
  {
    id: 72,
    symbol: "JD",
    name: "Jordanian Dinar",
    symbol_native: "د.أ.‏",
    decimal_digits: 3,
    rounding: 0,
    code: "JOD",
    name_plural: "Jordanian dinars",
    type: "fiat",
  },
  {
    id: 73,
    symbol: "¥",
    name: "Japanese Yen",
    symbol_native: "￥",
    decimal_digits: 0,
    rounding: 0,
    code: "JPY",
    name_plural: "Japanese yen",
    type: "fiat",
  },
  {
    id: 74,
    symbol: "Ksh",
    name: "Kenyan Shilling",
    symbol_native: "Ksh",
    decimal_digits: 2,
    rounding: 0,
    code: "KES",
    name_plural: "Kenyan shillings",
    type: "fiat",
  },
  {
    id: 75,
    symbol: "KGS",
    name: "Kyrgystani Som",
    symbol_native: "KGS",
    decimal_digits: 2,
    rounding: 0,
    code: "KGS",
    icon_name: "kgs",
    name_plural: "Kyrgystani Som",
    type: "fiat",
  },
  {
    id: 76,
    symbol: "KHR",
    name: "Cambodian Riel",
    symbol_native: "៛",
    decimal_digits: 2,
    rounding: 0,
    code: "KHR",
    name_plural: "Cambodian riels",
    type: "fiat",
  },
  {
    id: 77,
    symbol: "CF",
    name: "Comorian Franc",
    symbol_native: "FC",
    decimal_digits: 0,
    rounding: 0,
    code: "KMF",
    name_plural: "Comorian francs",
    type: "fiat",
  },
  {
    id: 78,
    symbol: "₩",
    name: "North Korean Won",
    symbol_native: "₩",
    decimal_digits: 2,
    rounding: 0,
    code: "KPW",
    icon_name: "kpw",
    name_plural: "North Korean Won",
    type: "fiat",
  },
  {
    id: 79,
    symbol: "₩",
    name: "South Korean Won",
    symbol_native: "₩",
    decimal_digits: 0,
    rounding: 0,
    code: "KRW",
    name_plural: "South Korean won",
    type: "fiat",
  },
  {
    id: 80,
    symbol: "KD",
    name: "Kuwaiti Dinar",
    symbol_native: "د.ك.‏",
    decimal_digits: 3,
    rounding: 0,
    code: "KWD",
    name_plural: "Kuwaiti dinars",
    type: "fiat",
  },
  {
    id: 81,
    symbol: "CI$",
    name: "Cayman Islands Dollar",
    symbol_native: "$‏",
    decimal_digits: 2,
    rounding: 0,
    code: "KYD",
    icon_name: "kyd",
    name_plural: "Cayman Islands Dollar",
    type: "fiat",
  },
  {
    id: 82,
    symbol: "KZT",
    name: "Kazakhstani Tenge",
    symbol_native: "тңг.",
    decimal_digits: 2,
    rounding: 0,
    code: "KZT",
    name_plural: "Kazakhstani tenges",
    type: "fiat",
  },
  {
    id: 83,
    symbol: "₭N",
    name: "Laotian Kip",
    symbol_native: "₭‏‏",
    decimal_digits: 0,
    rounding: 0,
    code: "LAK",
    name_plural: "Laotian Kip",
    type: "fiat",
  },
  {
    id: 84,
    symbol: "LB£",
    name: "Lebanese Pound",
    symbol_native: "ل.ل.‏",
    decimal_digits: 0,
    rounding: 0,
    code: "LBP",
    name_plural: "Lebanese pounds",
    type: "fiat",
  },
  {
    id: 85,
    symbol: "SLRs",
    name: "Sri Lankan Rupee",
    symbol_native: "SL Re",
    decimal_digits: 2,
    rounding: 0,
    code: "LKR",
    name_plural: "Sri Lankan rupees",
    type: "fiat",
  },
  {
    id: 86,
    symbol: "LD$",
    name: "Liberian Dollar",
    symbol_native: "L$",
    decimal_digits: 2,
    rounding: 0,
    code: "LRD",
    icon_name: "lrd",
    name_plural: "Liberian Dollar",
    type: "fiat",
  },
  {
    id: 87,
    symbol: "L",
    name: "Lesotho Loti",
    symbol_native: "M",
    decimal_digits: 2,
    rounding: 0,
    code: "LSL",
    icon_name: "lsl",
    name_plural: "Lesotho Loti",
    type: "fiat",
  },
  {
    id: 88,
    symbol: "Lt",
    name: "Lithuanian Litas",
    symbol_native: "Lt",
    decimal_digits: 2,
    rounding: 0,
    code: "LTL",
    name_plural: "Lithuanian litai",
    type: "fiat",
  },
  {
    id: 89,
    symbol: "Ls",
    name: "Latvian Lats",
    symbol_native: "Ls",
    decimal_digits: 2,
    rounding: 0,
    code: "LVL",
    name_plural: "Latvian lati",
    type: "fiat",
  },
  {
    id: 90,
    symbol: "LD",
    name: "Libyan Dinar",
    symbol_native: "د.ل.‏",
    decimal_digits: 3,
    rounding: 0,
    code: "LYD",
    name_plural: "Libyan dinars",
    type: "fiat",
  },
  {
    id: 91,
    symbol: "MAD",
    name: "Moroccan Dirham",
    symbol_native: "د.م.‏",
    decimal_digits: 2,
    rounding: 0,
    code: "MAD",
    name_plural: "Moroccan dirhams",
    type: "fiat",
  },
  {
    id: 92,
    symbol: "MDL",
    name: "Moldovan Leu",
    symbol_native: "MDL",
    decimal_digits: 2,
    rounding: 0,
    code: "MDL",
    name_plural: "Moldovan lei",
    type: "fiat",
  },
  {
    id: 93,
    symbol: "MGA",
    name: "Malagasy Ariary",
    symbol_native: "MGA",
    decimal_digits: 0,
    rounding: 0,
    code: "MGA",
    name_plural: "Malagasy Ariaries",
    type: "fiat",
  },
  {
    id: 94,
    symbol: "MKD",
    name: "Macedonian Denar",
    symbol_native: "MKD",
    decimal_digits: 2,
    rounding: 0,
    code: "MKD",
    name_plural: "Macedonian denari",
    type: "fiat",
  },
  {
    id: 95,
    symbol: "MMK",
    name: "Myanma Kyat",
    symbol_native: "K",
    decimal_digits: 0,
    rounding: 0,
    code: "MMK",
    name_plural: "Myanma kyats",
    type: "fiat",
  },
  {
    id: 96,
    symbol: "₮",
    name: "Mongolian Tugrik",
    symbol_native: "₮",
    decimal_digits: 2,
    rounding: 0,
    code: "MNT",
    icon_name: "mnt",
    name_plural: "Mongolian Tugrik",
    type: "fiat",
  },
  {
    id: 97,
    symbol: "MOP$",
    name: "Macanese Pataca",
    symbol_native: "MOP$",
    decimal_digits: 2,
    rounding: 0,
    code: "MOP",
    name_plural: "Macanese patacas",
    type: "fiat",
  },
  {
    id: 98,
    symbol: "UM",
    name: "Mauritanian ouguiya",
    symbol_native: "UM",
    decimal_digits: 2,
    rounding: 0,
    code: "MRO",
    name_plural: "Mauritanian ouguiyas",
    type: "fiat",
  },
  {
    id: 99,
    symbol: "MURs",
    name: "Mauritian Rupee",
    symbol_native: "MURs",
    decimal_digits: 0,
    rounding: 0,
    code: "MUR",
    name_plural: "Mauritian rupees",
    type: "fiat",
  },
  {
    id: 100,
    symbol: "MRf",
    name: "Maldivian Rufiyaa",
    symbol_native: "Rf",
    decimal_digits: 2,
    rounding: 0,
    code: "MVR",
    name_plural: "Maldivian Rufiyaa",
    type: "fiat",
  },
  {
    id: 101,
    symbol: "MK",
    name: "Malawian Kwacha",
    symbol_native: "MK",
    decimal_digits: 2,
    rounding: 0,
    code: "MWK",
    icon_name: "mwk",
    name_plural: "Malawian Kwacha",
    type: "fiat",
  },
  {
    id: 102,
    symbol: "MX$",
    name: "Mexican Peso",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "MXN",
    name_plural: "Mexican pesos",
    type: "fiat",
  },
  {
    id: 103,
    symbol: "RM",
    name: "Malaysian Ringgit",
    symbol_native: "RM",
    decimal_digits: 2,
    rounding: 0,
    code: "MYR",
    name_plural: "Malaysian ringgits",
    type: "fiat",
  },
  {
    id: 104,
    symbol: "MTn",
    name: "Mozambican Metical",
    symbol_native: "MTn",
    decimal_digits: 2,
    rounding: 0,
    code: "MZN",
    name_plural: "Mozambican meticals",
    type: "fiat",
  },
  {
    id: 105,
    symbol: "N$",
    name: "Namibian Dollar",
    symbol_native: "N$",
    decimal_digits: 2,
    rounding: 0,
    code: "NAD",
    name_plural: "Namibian dollars",
    type: "fiat",
  },
  {
    id: 106,
    symbol: "₦",
    name: "Nigerian Naira",
    symbol_native: "₦",
    decimal_digits: 2,
    rounding: 0,
    code: "NGN",
    name_plural: "Nigerian nairas",
    type: "fiat",
  },
  {
    id: 107,
    symbol: "C$",
    name: "Nicaraguan Córdoba",
    symbol_native: "C$",
    decimal_digits: 2,
    rounding: 0,
    code: "NIO",
    name_plural: "Nicaraguan córdobas",
    type: "fiat",
  },
  {
    id: 108,
    symbol: "Nkr",
    name: "Norwegian Krone",
    symbol_native: "kr",
    decimal_digits: 2,
    rounding: 0,
    code: "NOK",
    name_plural: "Norwegian kroner",
    type: "fiat",
  },
  {
    id: 109,
    symbol: "NPRs",
    name: "Nepalese Rupee",
    symbol_native: "नेरू",
    decimal_digits: 2,
    rounding: 0,
    code: "NPR",
    name_plural: "Nepalese rupees",
    type: "fiat",
  },
  {
    id: 110,
    symbol: "NZ$",
    name: "New Zealand Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "NZD",
    name_plural: "New Zealand dollars",
    type: "fiat",
  },
  {
    id: 111,
    symbol: "OMR",
    name: "Omani Rial",
    symbol_native: "ر.ع.‏",
    decimal_digits: 3,
    rounding: 0,
    code: "OMR",
    name_plural: "Omani rials",
    type: "fiat",
  },
  {
    id: 112,
    symbol: "B/.",
    name: "Panamanian Balboa",
    symbol_native: "B/.",
    decimal_digits: 2,
    rounding: 0,
    code: "PAB",
    name_plural: "Panamanian balboas",
    type: "fiat",
  },
  {
    id: 113,
    symbol: "S/.",
    name: "Peruvian Nuevo Sol",
    symbol_native: "S/.",
    decimal_digits: 2,
    rounding: 0,
    code: "PEN",
    name_plural: "Peruvian nuevos soles",
    type: "fiat",
  },
  {
    id: 114,
    symbol: "K",
    name: "Papua New Guinean Kina",
    symbol_native: "K",
    decimal_digits: 2,
    rounding: 0,
    code: "PGK",
    icon_name: "pgk",
    name_plural: "Papua New Guinean Kina",
    type: "fiat",
  },
  {
    id: 115,
    symbol: "₱",
    name: "Philippine Peso",
    symbol_native: "₱",
    decimal_digits: 2,
    rounding: 0,
    code: "PHP",
    name_plural: "Philippine pesos",
    type: "fiat",
  },
  {
    id: 116,
    symbol: "PKRs",
    name: "Pakistani Rupee",
    symbol_native: "₨",
    decimal_digits: 0,
    rounding: 0,
    code: "PKR",
    name_plural: "Pakistani rupees",
    type: "fiat",
  },
  {
    id: 117,
    symbol: "zł",
    name: "Polish Zloty",
    symbol_native: "zł",
    decimal_digits: 2,
    rounding: 0,
    code: "PLN",
    name_plural: "Polish zlotys",
    type: "fiat",
  },
  {
    id: 118,
    symbol: "₲",
    name: "Paraguayan Guarani",
    symbol_native: "₲",
    decimal_digits: 0,
    rounding: 0,
    code: "PYG",
    name_plural: "Paraguayan guaranis",
    type: "fiat",
  },
  {
    id: 119,
    symbol: "QR",
    name: "Qatari Rial",
    symbol_native: "ر.ق.‏",
    decimal_digits: 2,
    rounding: 0,
    code: "QAR",
    name_plural: "Qatari rials",
    type: "fiat",
  },
  {
    id: 120,
    symbol: "RON",
    name: "Romanian Leu",
    symbol_native: "RON",
    decimal_digits: 2,
    rounding: 0,
    code: "RON",
    name_plural: "Romanian lei",
    type: "fiat",
  },
  {
    id: 121,
    symbol: "din.",
    name: "Serbian Dinar",
    symbol_native: "дин.",
    decimal_digits: 0,
    rounding: 0,
    code: "RSD",
    name_plural: "Serbian dinars",
    type: "fiat",
  },
  {
    id: 122,
    symbol: "RUB",
    name: "Russian Ruble",
    symbol_native: "руб.",
    decimal_digits: 2,
    rounding: 0,
    code: "RUB",
    name_plural: "Russian rubles",
    type: "fiat",
  },
  {
    id: 123,
    symbol: "RWF",
    name: "Rwandan Franc",
    symbol_native: "FR",
    decimal_digits: 0,
    rounding: 0,
    code: "RWF",
    name_plural: "Rwandan francs",
    type: "fiat",
  },
  {
    id: 124,
    symbol: "SR",
    name: "Saudi Riyal",
    symbol_native: "ر.س.‏",
    decimal_digits: 2,
    rounding: 0,
    code: "SAR",
    name_plural: "Saudi riyals",
    type: "fiat",
  },
  {
    id: 125,
    symbol: "SI$",
    name: "Solomon Islands Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "SBD",
    icon_name: "sbd",
    name_plural: "Solomon Islands Dollars",
    type: "fiat",
  },
  {
    id: 126,
    symbol: "SRe",
    name: "Seychellois Rupee",
    symbol_native: "SR",
    decimal_digits: 2,
    rounding: 0,
    code: "SCR",
    icon_name: "scr",
    name_plural: "Seychellois Rupees",
    type: "fiat",
  },
  {
    id: 127,
    symbol: "SDG",
    name: "Sudanese Pound",
    symbol_native: "SDG",
    decimal_digits: 2,
    rounding: 0,
    code: "SDG",
    name_plural: "Sudanese pounds",
    type: "fiat",
  },
  {
    id: 128,
    symbol: "Skr",
    name: "Swedish Krona",
    symbol_native: "kr",
    decimal_digits: 2,
    rounding: 0,
    code: "SEK",
    name_plural: "Swedish kronor",
    type: "fiat",
  },
  {
    id: 129,
    symbol: "S$",
    name: "Singapore Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "SGD",
    name_plural: "Singapore dollars",
    type: "fiat",
  },
  {
    id: 130,
    symbol: "£",
    name: "Saint Helena Pound",
    symbol_native: "£",
    decimal_digits: 2,
    rounding: 0,
    code: "SHP",
    icon_name: "shp",
    name_plural: "Saint Helena Pounds",
    type: "fiat",
  },
  {
    id: 131,
    symbol: "Le",
    name: "Sierra Leonean Leone",
    symbol_native: "Le",
    decimal_digits: 2,
    rounding: 0,
    code: "SLL",
    icon_name: "sll",
    name_plural: "Sierra Leonean Leone",
    type: "fiat",
  },
  {
    id: 132,
    symbol: "Ssh",
    name: "Somali Shilling",
    symbol_native: "Ssh",
    decimal_digits: 0,
    rounding: 0,
    code: "SOS",
    name_plural: "Somali shillings",
    type: "fiat",
  },
  {
    id: 133,
    symbol: "$",
    name: "Surinamese Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "SRD",
    icon_name: "srd",
    name_plural: "Surinamese Dollar",
    type: "fiat",
  },
  {
    id: 134,
    symbol: "Db",
    name: "São Tomé and Príncipe dobra",
    symbol_native: "Db",
    decimal_digits: 2,
    rounding: 0,
    code: "STD",
    name_plural: "São Tomé and Príncipe dobras",
    type: "fiat",
  },
  {
    id: 135,
    symbol: "₡",
    name: "Salvadoran Colón",
    symbol_native: "₡",
    decimal_digits: 2,
    rounding: 0,
    code: "SVC",
    icon_name: "svc",
    name_plural: "Salvadoran Colón",
    type: "fiat",
  },
  {
    id: 136,
    symbol: "SY£",
    name: "Syrian Pound",
    symbol_native: "ل.س.‏",
    decimal_digits: 0,
    rounding: 0,
    code: "SYP",
    name_plural: "Syrian pounds",
    type: "fiat",
  },
  {
    id: 137,
    symbol: "L",
    name: "Swazi Lilangeni",
    symbol_native: "E‏",
    decimal_digits: 2,
    rounding: 0,
    code: "SZL",
    icon_name: "szl",
    name_plural: "Swazi Lilangeni",
    type: "fiat",
  },
  {
    id: 138,
    symbol: "฿",
    name: "Thai Baht",
    symbol_native: "฿",
    decimal_digits: 2,
    rounding: 0,
    code: "THB",
    name_plural: "Thai baht",
    type: "fiat",
  },
  {
    id: 139,
    symbol: "TJS",
    name: "Tajikistani Somoni",
    symbol_native: "TJS",
    decimal_digits: 2,
    rounding: 0,
    code: "TJS",
    icon_name: "tjs",
    name_plural: "Tajikistani Somoni",
    type: "fiat",
  },
  {
    id: 140,
    symbol: "T",
    name: "Turkmenistani Manat",
    symbol_native: "T‏",
    decimal_digits: 2,
    rounding: 0,
    code: "TMT",
    icon_name: "tmt",
    name_plural: "Turkmenistani Manat",
    type: "fiat",
  },
  {
    id: 141,
    symbol: "DT",
    name: "Tunisian Dinar",
    symbol_native: "د.ت.‏",
    decimal_digits: 3,
    rounding: 0,
    code: "TND",
    name_plural: "Tunisian dinars",
    type: "fiat",
  },
  {
    id: 142,
    symbol: "T$",
    name: "Tongan Paʻanga",
    symbol_native: "T$",
    decimal_digits: 2,
    rounding: 0,
    code: "TOP",
    name_plural: "Tongan paʻanga",
    type: "fiat",
  },
  {
    id: 143,
    symbol: "TL",
    name: "Turkish Lira",
    symbol_native: "TL",
    decimal_digits: 2,
    rounding: 0,
    code: "TRY",
    name_plural: "Turkish Lira",
    type: "fiat",
  },
  {
    id: 144,
    symbol: "TT$",
    name: "Trinidad and Tobago Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "TTD",
    name_plural: "Trinidad and Tobago dollars",
    type: "fiat",
  },
  {
    id: 145,
    symbol: "NT$",
    name: "New Taiwan Dollar",
    symbol_native: "NT$",
    decimal_digits: 2,
    rounding: 0,
    code: "TWD",
    name_plural: "New Taiwan dollars",
    type: "fiat",
  },
  {
    id: 146,
    symbol: "TSh",
    name: "Tanzanian Shilling",
    symbol_native: "TSh",
    decimal_digits: 0,
    rounding: 0,
    code: "TZS",
    name_plural: "Tanzanian shillings",
    type: "fiat",
  },
  {
    id: 147,
    symbol: "₴",
    name: "Ukrainian Hryvnia",
    symbol_native: "₴",
    decimal_digits: 2,
    rounding: 0,
    code: "UAH",
    name_plural: "Ukrainian hryvnias",
    type: "fiat",
  },
  {
    id: 148,
    symbol: "USh",
    name: "Ugandan Shilling",
    symbol_native: "USh",
    decimal_digits: 0,
    rounding: 0,
    code: "UGX",
    name_plural: "Ugandan shillings",
    type: "fiat",
  },
  {
    id: 149,
    symbol: "$",
    name: "US Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "USD",
    name_plural: "US dollars",
    type: "fiat",
  },
  {
    id: 150,
    symbol: "$U",
    name: "Uruguayan Peso",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "UYU",
    name_plural: "Uruguayan pesos",
    type: "fiat",
  },
  {
    id: 151,
    symbol: "UZS",
    name: "Uzbekistan Som",
    symbol_native: "UZS",
    decimal_digits: 0,
    rounding: 0,
    code: "UZS",
    name_plural: "Uzbekistan som",
    type: "fiat",
  },
  {
    id: 152,
    symbol: "Bs.F.",
    name: "Venezuelan Bolívar",
    symbol_native: "Bs.F.",
    decimal_digits: 2,
    rounding: 0,
    code: "VEF",
    name_plural: "Venezuelan bolívars",
    type: "fiat",
  },
  {
    id: 153,
    symbol: "₫",
    name: "Vietnamese Dong",
    symbol_native: "₫",
    decimal_digits: 0,
    rounding: 0,
    code: "VND",
    name_plural: "Vietnamese dong",
    type: "fiat",
  },
  {
    id: 154,
    symbol: "VUV",
    name: "Vanuatu Vatu",
    symbol_native: "VT",
    decimal_digits: 0,
    rounding: 0,
    code: "VUV",
    icon_name: "vuv",
    name_plural: "Vanuatu Vatu",
    type: "fiat",
  },
  {
    id: 155,
    symbol: "WS$",
    name: "Samoan Tala",
    symbol_native: "T",
    decimal_digits: 2,
    rounding: 0,
    code: "WST",
    icon_name: "wst",
    name_plural: "Samoan Tala",
    type: "fiat",
  },
  {
    id: 156,
    symbol: "FCFA",
    name: "CFA Franc BEAC",
    symbol_native: "FCFA",
    decimal_digits: 0,
    rounding: 0,
    code: "XAF",
    name_plural: "CFA francs BEAC",
    type: "fiat",
  },
  {
    id: 157,
    symbol: "XAG",
    name: "Silver Ounce",
    symbol_native: "XAG",
    decimal_digits: 2,
    rounding: 0,
    code: "XAG",
    name_plural: "Silver Ounces",
    type: "metal",
  },
  {
    id: 158,
    symbol: "XAU",
    name: "Gold Ounce",
    symbol_native: "XAU",
    decimal_digits: 2,
    rounding: 0,
    code: "XAU",
    name_plural: "Gold Ounces",
    type: "metal",
  },
  {
    id: 159,
    symbol: "EC$",
    name: "East Caribbean Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "XCD",
    icon_name: "xcd",
    name_plural: "East Caribbean Dollars",
    type: "fiat",
  },
  {
    id: 160,
    symbol: "SDR",
    name: "Special drawing rights",
    symbol_native: "SDR",
    decimal_digits: 2,
    rounding: 0,
    code: "XDR",
    name_plural: "Special drawing rights",
    type: "fiat",
  },
  {
    id: 161,
    symbol: "CFA",
    name: "CFA Franc BCEAO",
    symbol_native: "CFA",
    decimal_digits: 0,
    rounding: 0,
    code: "XOF",
    name_plural: "CFA francs BCEAO",
    type: "fiat",
  },
  {
    id: 162,
    symbol: "CFP",
    name: "CFP Franc",
    symbol_native: "CFP",
    decimal_digits: 0,
    rounding: 0,
    code: "XPF",
    icon_name: "xpf",
    name_plural: "CFP francs",
    type: "fiat",
  },
  {
    id: 163,
    symbol: "YR",
    name: "Yemeni Rial",
    symbol_native: "ر.ي.‏",
    decimal_digits: 0,
    rounding: 0,
    code: "YER",
    name_plural: "Yemeni rials",
    type: "fiat",
  },
  {
    id: 164,
    symbol: "R",
    name: "South African Rand",
    symbol_native: "R",
    decimal_digits: 2,
    rounding: 0,
    code: "ZAR",
    name_plural: "South African rand",
    type: "fiat",
  },
  {
    id: 165,
    symbol: "ZK",
    name: "Zambian Kwacha",
    symbol_native: "ZK",
    decimal_digits: 0,
    rounding: 0,
    code: "ZMK",
    name_plural: "Zambian kwachas",
    type: "fiat",
  },
  {
    id: 166,
    symbol: "ZK",
    name: "Zambian Kwacha",
    symbol_native: "ZK",
    decimal_digits: 0,
    rounding: 0,
    code: "ZMW",
    name_plural: "Zambian kwachas",
    type: "fiat",
  },
  {
    id: 167,
    symbol: "ZWL",
    name: "Zimbabwean dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "ZWL",
    name_plural: "Zimbabwean dollars",
    type: "fiat",
  },
  {
    id: 168,
    symbol: "XPT",
    name: "Platinum Ounce",
    symbol_native: "XPT",
    decimal_digits: 6,
    rounding: 0,
    code: "XPT",
    name_plural: "Platinum Ounces",
    type: "metal",
  },
  {
    id: 169,
    symbol: "XPD",
    name: "Palladium Ounce",
    symbol_native: "XPD",
    decimal_digits: 6,
    rounding: 0,
    code: "XPD",
    name_plural: "Palladium Ounces",
    type: "metal",
  },
  {
    id: 170,
    symbol: "₿",
    name: "Bitcoin",
    symbol_native: "₿",
    decimal_digits: 8,
    rounding: 0,
    code: "BTC",
    name_plural: "Bitcoins",
    type: "crypto",
  },
  {
    id: 171,
    symbol: "Ξ",
    name: "Ethereum",
    symbol_native: "Ξ",
    decimal_digits: 18,
    rounding: 0,
    code: "ETH",
    name_plural: "Ethereum",
    type: "crypto",
  },
  {
    id: 172,
    symbol: "BNB",
    name: "Binance",
    symbol_native: "BNB",
    decimal_digits: 8,
    rounding: 0,
    code: "BNB",
    name_plural: "Binance",
    type: "crypto",
  },
  {
    id: 173,
    symbol: "XRP",
    name: "Ripple",
    symbol_native: "XRP",
    decimal_digits: 6,
    rounding: 0,
    code: "XRP",
    name_plural: "Ripple",
    type: "crypto",
  },
  {
    id: 174,
    symbol: "SOL",
    name: "Solana",
    symbol_native: "SOL",
    decimal_digits: 9,
    rounding: 0,
    code: "SOL",
    name_plural: "Solana",
    type: "crypto",
  },
  {
    id: 175,
    symbol: "DOT",
    name: "Polkadot",
    symbol_native: "DOT",
    decimal_digits: 10,
    rounding: 0,
    code: "DOT",
    name_plural: "Polkadot",
    type: "crypto",
  },
  {
    id: 176,
    symbol: "AVAX",
    name: "Avalanche",
    symbol_native: "AVAX",
    decimal_digits: 18,
    rounding: 0,
    code: "AVAX",
    name_plural: "Avalanche",
    type: "crypto",
  },
  {
    id: 177,
    symbol: "MATIC",
    name: "Matic Token",
    symbol_native: "MATIC",
    decimal_digits: 18,
    rounding: 0,
    code: "MATIC",
    name_plural: "Matic Tokens",
    type: "crypto",
  },
  {
    id: 178,
    symbol: "Ł",
    name: "Litecoin",
    symbol_native: "Ł",
    decimal_digits: 8,
    rounding: 0,
    code: "LTC",
    name_plural: "Litecoins",
    type: "crypto",
  },
  {
    id: 179,
    symbol: "ADA",
    name: "Cardano",
    symbol_native: "ADA",
    decimal_digits: 6,
    rounding: 0,
    code: "ADA",
    name_plural: "Cardanos",
    type: "crypto",
  },
  {
    id: 180,
    symbol: "USDT",
    name: "Tether",
    symbol_native: "USDT",
    decimal_digits: 2,
    rounding: 0,
    code: "USDT",
    name_plural: "Tethers",
    type: "crypto",
  },
  {
    id: 181,
    symbol: "USDC",
    name: "USD Coin",
    symbol_native: "USDC",
    decimal_digits: 2,
    rounding: 0,
    code: "USDC",
    name_plural: "USD Coins",
    type: "crypto",
  },
  {
    id: 182,
    symbol: "DAI",
    name: "Dai",
    symbol_native: "DAI",
    decimal_digits: 2,
    rounding: 0,
    code: "DAI",
    name_plural: "Dais",
    type: "crypto",
  },
  {
    id: 183,
    symbol: "ARB",
    name: "Arbitrum",
    symbol_native: "ARB",
    decimal_digits: 8,
    rounding: 0,
    code: "ARB",
    name_plural: "Arbitrums",
    type: "crypto",
  },
  {
    id: 184,
    symbol: "OP",
    name: "Optimism",
    symbol_native: "OP",
    decimal_digits: 8,
    rounding: 0,
    code: "OP",
    name_plural: "Optimism",
    type: "crypto",
  },
  {
    id: 185,
    symbol: "Bs.S.",
    name: "Venezuelan Bolívar",
    symbol_native: "Bs.S.",
    decimal_digits: 2,
    rounding: 0,
    code: "VES",
    name_plural: "Venezuelan bolívars",
    type: "fiat",
  },
  {
    id: 186,
    symbol: "STN",
    name: "São Tomé and Príncipe dobra",
    symbol_native: "STN",
    decimal_digits: 2,
    rounding: 0,
    code: "STN",
    name_plural: "dobra",
    type: "fiat",
  },
  {
    id: 187,
    symbol: "MRU",
    name: "Mauritanian ouguiya",
    symbol_native: "MRU",
    decimal_digits: 2,
    rounding: 0,
    code: "MRU",
    name_plural: "ouguiya",
    type: "fiat",
  },
];

const insert = async () => {
  try {
    let currencyFormatted = currencies.map((currency) => {
      return {
        id: currency.id,
        name: currency.name
          .replace(" ", "")
          .replace(" ", "")
          .replace("", "")
          .replace("", ""),
        code: currency.code,
        symbol: currency.symbol,
        exchangeRate: 1,
        decimalDigits: currency.decimal_digits,
      };
    });

    // console.log(currencyFormatted);

    await db
      .createQueryBuilder()
      .insert()
      .into(Currency)
      .values(currencyFormatted)
      .orUpdate(["name", "code", "symbol", "decimal_digits"], ["id"], {
        skipUpdateIfNoValuesChanged: true,
      })
      .execute();
  } catch (error) {
    console.error(error);
    throw error;
  }
};

export default insert;
