import db, { Currency, CurrencyType } from "../";

const currencyTypes = [
  { id: 1, name: "fiat" },
  { id: 2, name: "crypto" },
  { id: 3, name: "metal" },
];

const currencies = [
  {
    id: 1,
    symbol: "AED",
    name: "United Arab Emirates Dirham",
    symbolNative: "د.إ",
    decimalDigits: 2,
    rounding: 0,
    code: "AED",
    namePlural: "UAE dirhams",
    typeId: 1,
  },
  {
    id: 2,
    symbol: "Af",
    name: "Afghan Afghani",
    symbolNative: "؋",
    decimalDigits: 0,
    rounding: 0,
    code: "AFN",
    namePlural: "Afghan Afghanis",
    typeId: 1,
  },
  {
    id: 3,
    symbol: "ALL",
    name: "Albanian Lek",
    symbolNative: "Lek",
    decimalDigits: 0,
    rounding: 0,
    code: "ALL",
    namePlural: "Albanian lekë",
    typeId: 1,
  },
  {
    id: 4,
    symbol: "AMD",
    name: "Armenian Dram",
    symbolNative: "դր.",
    decimalDigits: 0,
    rounding: 0,
    code: "AMD",
    namePlural: "Armenian drams",
    typeId: 1,
  },
  {
    id: 5,
    symbol: "ƒ",
    name: "NL Antillean Guilder",
    symbolNative: "NAƒ",
    decimalDigits: 2,
    rounding: 0,
    code: "ANG",
    namePlural: "NL Antillean Guilders",
    typeId: 1,
  },
  {
    id: 6,
    symbol: "Kz",
    name: "Angolan Kwanza",
    symbolNative: "Kz",
    decimalDigits: 2,
    rounding: 0,
    code: "AOA",
    namePlural: "Angolan Kwanza",
    typeId: 1,
  },
  {
    id: 7,
    symbol: "AR$",
    name: "Argentine Peso",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "ARS",
    namePlural: "Argentine pesos",
    typeId: 1,
  },
  {
    id: 8,
    symbol: "AU$",
    name: "Australian Dollar",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "AUD",
    namePlural: "Australian dollars",
    typeId: 1,
  },
  {
    id: 9,
    symbol: "Afl.",
    name: "Aruban Florin",
    symbolNative: "Afl.",
    decimalDigits: 2,
    rounding: 0,
    code: "AWG",
    namePlural: "Aruban Florin",
    typeId: 1,
  },
  {
    id: 10,
    symbol: "man.",
    name: "Azerbaijani Manat",
    symbolNative: "ман.",
    decimalDigits: 2,
    rounding: 0,
    code: "AZN",
    namePlural: "Azerbaijani manats",
    typeId: 1,
  },
  {
    id: 11,
    symbol: "KM",
    name: "Bosnia-Herzegovina Convertible Mark",
    symbolNative: "KM",
    decimalDigits: 2,
    rounding: 0,
    code: "BAM",
    namePlural: "Bosnia-Herzegovina convertible marks",
    typeId: 1,
  },
  {
    id: 12,
    symbol: "Bds$",
    name: "Barbadian Dollar",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "BBD",
    namePlural: "Barbadian Dollars",
    typeId: 1,
  },
  {
    id: 13,
    symbol: "Tk",
    name: "Bangladeshi Taka",
    symbolNative: "৳",
    decimalDigits: 2,
    rounding: 0,
    code: "BDT",
    namePlural: "Bangladeshi takas",
    typeId: 1,
  },
  {
    id: 14,
    symbol: "BGN",
    name: "Bulgarian Lev",
    symbolNative: "лв.",
    decimalDigits: 2,
    rounding: 0,
    code: "BGN",
    namePlural: "Bulgarian leva",
    typeId: 1,
  },
  {
    id: 15,
    symbol: "BD",
    name: "Bahraini Dinar",
    symbolNative: "د.ب.",
    decimalDigits: 3,
    rounding: 0,
    code: "BHD",
    namePlural: "Bahraini dinars",
    typeId: 1,
  },
  {
    id: 16,
    symbol: "FBu",
    name: "Burundian Franc",
    symbolNative: "FBu",
    decimalDigits: 0,
    rounding: 0,
    code: "BIF",
    namePlural: "Burundian francs",
    typeId: 1,
  },
  {
    id: 17,
    symbol: "BD$",
    name: "Bermudan Dollar",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "BMD",
    namePlural: "Bermudan Dollars",
    typeId: 1,
  },
  {
    id: 18,
    symbol: "BN$",
    name: "Brunei Dollar",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "BND",
    namePlural: "Brunei dollars",
    typeId: 1,
  },
  {
    id: 19,
    symbol: "Bs",
    name: "Bolivian Boliviano",
    symbolNative: "Bs",
    decimalDigits: 2,
    rounding: 0,
    code: "BOB",
    namePlural: "Bolivian bolivianos",
    typeId: 1,
  },
  {
    id: 20,
    symbol: "R$",
    name: "Brazilian Real",
    symbolNative: "R$",
    decimalDigits: 2,
    rounding: 0,
    code: "BRL",
    namePlural: "Brazilian reals",
    typeId: 1,
  },
  {
    id: 21,
    symbol: "B$",
    name: "Bahamian Dollar",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "BSD",
    namePlural: "Bahamian Dollars",
    typeId: 1,
  },
  {
    id: 22,
    symbol: "Nu.",
    name: "Bhutanese Ngultrum",
    symbolNative: "Nu.",
    decimalDigits: 2,
    rounding: 0,
    code: "BTN",
    namePlural: "Bhutanese Ngultrum",
    typeId: 1,
  },
  {
    id: 23,
    symbol: "BWP",
    name: "Botswanan Pula",
    symbolNative: "P",
    decimalDigits: 2,
    rounding: 0,
    code: "BWP",
    namePlural: "Botswanan pulas",
    typeId: 1,
  },
  {
    id: 24,
    symbol: "Br",
    name: "Belarusian ruble",
    symbolNative: "Br",
    decimalDigits: 2,
    rounding: 0,
    code: "BYN",
    namePlural: "Belarusian rubles",
    typeId: 1,
  },
  {
    id: 25,
    symbol: "BYR",
    name: "Belarusian Ruble",
    symbolNative: "BYR",
    decimalDigits: 0,
    rounding: 0,
    code: "BYR",
    namePlural: "Belarusian rubles",
    typeId: 1,
  },
  {
    id: 26,
    symbol: "BZ$",
    name: "Belize Dollar",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "BZD",
    namePlural: "Belize dollars",
    typeId: 1,
  },
  {
    id: 27,
    symbol: "CA$",
    name: "Canadian Dollar",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "CAD",
    namePlural: "Canadian dollars",
    typeId: 1,
  },
  {
    id: 28,
    symbol: "CDF",
    name: "Congolese Franc",
    symbolNative: "FrCD",
    decimalDigits: 2,
    rounding: 0,
    code: "CDF",
    namePlural: "Congolese francs",
    typeId: 1,
  },
  {
    id: 29,
    symbol: "CHF",
    name: "Swiss Franc",
    symbolNative: "CHF",
    decimalDigits: 2,
    rounding: 0,
    code: "CHF",
    namePlural: "Swiss francs",
    typeId: 1,
  },
  {
    id: 30,
    symbol: "UF",
    name: "Unidad de Fomento",
    symbolNative: "UF",
    decimalDigits: 2,
    rounding: 0,
    code: "CLF",
    namePlural: "Unidad de Fomentos",
    typeId: 1,
  },
  {
    id: 31,
    symbol: "CL$",
    name: "Chilean Peso",
    symbolNative: "$",
    decimalDigits: 0,
    rounding: 0,
    code: "CLP",
    namePlural: "Chilean pesos",
    typeId: 1,
  },
  {
    id: 32,
    symbol: "CN¥",
    name: "Chinese Yuan",
    symbolNative: "CN¥",
    decimalDigits: 2,
    rounding: 0,
    code: "CNY",
    namePlural: "Chinese yuan",
    typeId: 1,
  },
  {
    id: 33,
    symbol: "CO$",
    name: "Coombian Peso",
    symbolNative: "$",
    decimalDigits: 0,
    rounding: 0,
    code: "COP",
    namePlural: "Colombian pesos",
    typeId: 1,
  },
  {
    id: 34,
    symbol: "₡",
    name: "Costa Rican Colón",
    symbolNative: "₡",
    decimalDigits: 0,
    rounding: 0,
    code: "CRC",
    namePlural: "Costa Rican colóns",
    typeId: 1,
  },
  {
    id: 35,
    symbol: "CUC$",
    name: "Cuban Convertible Peso",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "CUC",
    namePlural: "Cuban Convertible Peso",
    typeId: 1,
  },
  {
    id: 36,
    symbol: "$MN",
    name: "Cuban Peso",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "CUP",
    namePlural: "Cuban Peso",
    typeId: 1,
  },
  {
    id: 37,
    symbol: "CV$",
    name: "Cape Verdean Escudo",
    symbolNative: "CV$",
    decimalDigits: 2,
    rounding: 0,
    code: "CVE",
    namePlural: "Cape Verdean escudos",
    typeId: 1,
  },
  {
    id: 38,
    symbol: "Kč",
    name: "Czech Republic Koruna",
    symbolNative: "Kč",
    decimalDigits: 2,
    rounding: 0,
    code: "CZK",
    namePlural: "Czech Republic korunas",
    typeId: 1,
  },
  {
    id: 39,
    symbol: "Fdj",
    name: "Djiboutian Franc",
    symbolNative: "Fdj",
    decimalDigits: 0,
    rounding: 0,
    code: "DJF",
    namePlural: "Djiboutian francs",
    typeId: 1,
  },
  {
    id: 40,
    symbol: "Dkr",
    name: "Danish Krone",
    symbolNative: "kr",
    decimalDigits: 2,
    rounding: 0,
    code: "DKK",
    namePlural: "Danish kroner",
    typeId: 1,
  },
  {
    id: 41,
    symbol: "RD$",
    name: "Dominican Peso",
    symbolNative: "RD$",
    decimalDigits: 2,
    rounding: 0,
    code: "DOP",
    namePlural: "Dominican pesos",
    typeId: 1,
  },
  {
    id: 42,
    symbol: "DA",
    name: "Algerian Dinar",
    symbolNative: "د.ج.",
    decimalDigits: 2,
    rounding: 0,
    code: "DZD",
    namePlural: "Algerian dinars",
    typeId: 1,
  },
  {
    id: 43,
    symbol: "EGP",
    name: "Egyptian Pound",
    symbolNative: "ج.م.",
    decimalDigits: 2,
    rounding: 0,
    code: "EGP",
    namePlural: "Egyptian pounds",
    typeId: 1,
  },
  {
    id: 44,
    symbol: "Nfk",
    name: "Eritrean Nakfa",
    symbolNative: "Nfk",
    decimalDigits: 2,
    rounding: 0,
    code: "ERN",
    namePlural: "Eritrean nakfas",
    typeId: 1,
  },
  {
    id: 45,
    symbol: "Br",
    name: "Ethiopian Birr",
    symbolNative: "Br",
    decimalDigits: 2,
    rounding: 0,
    code: "ETB",
    namePlural: "Ethiopian birrs",
    typeId: 1,
  },
  {
    id: 46,
    symbol: "€",
    name: "Euro",
    symbolNative: "€",
    decimalDigits: 2,
    rounding: 0,
    code: "EUR",
    namePlural: "Euros",
    typeId: 1,
  },
  {
    id: 47,
    symbol: "FJ$",
    name: "Fijian Dollar",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "FJD",
    namePlural: "Fijian Dollar",
    typeId: 1,
  },
  {
    id: 48,
    symbol: "FK£",
    name: "Falkland Islands Pound",
    symbolNative: "£",
    decimalDigits: 2,
    rounding: 0,
    code: "FKP",
    namePlural: "Falkland Islands Pound",
    typeId: 1,
  },
  {
    id: 49,
    symbol: "£",
    name: "British Pound Sterling",
    symbolNative: "£",
    decimalDigits: 2,
    rounding: 0,
    code: "GBP",
    namePlural: "British pounds sterling",
    typeId: 1,
  },
  {
    id: 50,
    symbol: "GEL",
    name: "Georgian Lari",
    symbolNative: "GEL",
    decimalDigits: 2,
    rounding: 0,
    code: "GEL",
    namePlural: "Georgian laris",
    typeId: 1,
  },
  {
    id: 51,
    symbol: "£",
    name: "Guernsey pound",
    symbolNative: "£",
    decimalDigits: 2,
    rounding: 0,
    code: "GGP",
    namePlural: "Guernsey pounds",
    typeId: 1,
  },
  {
    id: 52,
    symbol: "GH₵",
    name: "Ghanaian Cedi",
    symbolNative: "GH₵",
    decimalDigits: 2,
    rounding: 0,
    code: "GHS",
    namePlural: "Ghanaian cedis",
    typeId: 1,
  },
  {
    id: 53,
    symbol: "£",
    name: "Gibraltar Pound",
    symbolNative: "£",
    decimalDigits: 2,
    rounding: 0,
    code: "GIP",
    namePlural: "Gibraltar Pounds",
    typeId: 1,
  },
  {
    id: 54,
    symbol: "D",
    name: "Gambian Dalasi",
    symbolNative: "D",
    decimalDigits: 2,
    rounding: 0,
    code: "GMD",
    namePlural: "Gambian Dalasi",
    typeId: 1,
  },
  {
    id: 55,
    symbol: "FG",
    name: "Guinean Franc",
    symbolNative: "FG",
    decimalDigits: 0,
    rounding: 0,
    code: "GNF",
    namePlural: "Guinean francs",
    typeId: 1,
  },
  {
    id: 56,
    symbol: "GTQ",
    name: "Guatemalan Quetzal",
    symbolNative: "Q",
    decimalDigits: 2,
    rounding: 0,
    code: "GTQ",
    namePlural: "Guatemalan quetzals",
    typeId: 1,
  },
  {
    id: 57,
    symbol: "G$",
    name: "Guyanaese Dollar",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "GYD",
    namePlural: "Guyanaese Dollar",
    typeId: 1,
  },
  {
    id: 58,
    symbol: "HK$",
    name: "Hong Kong Dollar",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "HKD",
    namePlural: "Hong Kong dollars",
    typeId: 1,
  },
  {
    id: 59,
    symbol: "HNL",
    name: "Honduran Lempira",
    symbolNative: "L",
    decimalDigits: 2,
    rounding: 0,
    code: "HNL",
    namePlural: "Honduran lempiras",
    typeId: 1,
  },
  {
    id: 60,
    symbol: "kn",
    name: "Croatian Kuna",
    symbolNative: "kn",
    decimalDigits: 2,
    rounding: 0,
    code: "HRK",
    namePlural: "Croatian kunas",
    typeId: 1,
  },
  {
    id: 61,
    symbol: "G",
    name: "Haitian Gourde",
    symbolNative: "G",
    decimalDigits: 2,
    rounding: 0,
    code: "HTG",
    namePlural: "Haitian Gourde",
    typeId: 1,
  },
  {
    id: 62,
    symbol: "Ft",
    name: "Hungarian Forint",
    symbolNative: "Ft",
    decimalDigits: 0,
    rounding: 0,
    code: "HUF",
    namePlural: "Hungarian forints",
    typeId: 1,
  },
  {
    id: 63,
    symbol: "Rp",
    name: "Indonesian Rupiah",
    symbolNative: "Rp",
    decimalDigits: 0,
    rounding: 0,
    code: "IDR",
    namePlural: "Indonesian rupiahs",
    typeId: 1,
  },
  {
    id: 64,
    symbol: "₪",
    name: "Israeli New Sheqel",
    symbolNative: "₪",
    decimalDigits: 2,
    rounding: 0,
    code: "ILS",
    namePlural: "Israeli new sheqels",
    typeId: 1,
  },
  {
    id: 65,
    symbol: "£",
    name: "Manx pound",
    symbolNative: "£",
    decimalDigits: 2,
    rounding: 0,
    code: "IMP",
    namePlural: "Manx pounds",
    typeId: 1,
  },
  {
    id: 66,
    symbol: "Rs",
    name: "Indian Rupee",
    symbolNative: "টকা",
    decimalDigits: 2,
    rounding: 0,
    code: "INR",
    namePlural: "Indian rupees",
    typeId: 1,
  },
  {
    id: 67,
    symbol: "IQD",
    name: "Iraqi Dinar",
    symbolNative: "د.ع.",
    decimalDigits: 0,
    rounding: 0,
    code: "IQD",
    namePlural: "Iraqi dinars",
    typeId: 1,
  },
  {
    id: 68,
    symbol: "IRR",
    name: "Iranian Rial",
    symbolNative: "﷼",
    decimalDigits: 0,
    rounding: 0,
    code: "IRR",
    namePlural: "Iranian rials",
    typeId: 1,
  },
  {
    id: 69,
    symbol: "Ikr",
    name: "Icelandic Króna",
    symbolNative: "kr",
    decimalDigits: 0,
    rounding: 0,
    code: "ISK",
    namePlural: "Icelandic krónur",
    typeId: 1,
  },
  {
    id: 70,
    symbol: "£",
    name: "Jersey pound",
    symbolNative: "£",
    decimalDigits: 2,
    rounding: 0,
    code: "JEP",
    namePlural: "Jersey pound",
    typeId: 1,
  },
  {
    id: 71,
    symbol: "J$",
    name: "Jamaican Dollar",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "JMD",
    namePlural: "Jamaican dollars",
    typeId: 1,
  },
  {
    id: 72,
    symbol: "JD",
    name: "Jordanian Dinar",
    symbolNative: "د.أ.",
    decimalDigits: 3,
    rounding: 0,
    code: "JOD",
    namePlural: "Jordanian dinars",
    typeId: 1,
  },
  {
    id: 73,
    symbol: "¥",
    name: "Japanese Yen",
    symbolNative: "￥",
    decimalDigits: 0,
    rounding: 0,
    code: "JPY",
    namePlural: "Japanese yen",
    typeId: 1,
  },
  {
    id: 74,
    symbol: "Ksh",
    name: "Kenyan Shilling",
    symbolNative: "Ksh",
    decimalDigits: 2,
    rounding: 0,
    code: "KES",
    namePlural: "Kenyan shillings",
    typeId: 1,
  },
  {
    id: 75,
    symbol: "KGS",
    name: "Kyrgystani Som",
    symbolNative: "KGS",
    decimalDigits: 2,
    rounding: 0,
    code: "KGS",
    namePlural: "Kyrgystani Som",
    typeId: 1,
  },
  {
    id: 76,
    symbol: "KHR",
    name: "Cambodian Riel",
    symbolNative: "៛",
    decimalDigits: 2,
    rounding: 0,
    code: "KHR",
    namePlural: "Cambodian riels",
    typeId: 1,
  },
  {
    id: 77,
    symbol: "CF",
    name: "Comorian Franc",
    symbolNative: "FC",
    decimalDigits: 0,
    rounding: 0,
    code: "KMF",
    namePlural: "Comorian francs",
    typeId: 1,
  },
  {
    id: 78,
    symbol: "₩",
    name: "North Korean Won",
    symbolNative: "₩",
    decimalDigits: 2,
    rounding: 0,
    code: "KPW",
    namePlural: "North Korean Won",
    typeId: 1,
  },
  {
    id: 79,
    symbol: "₩",
    name: "South Korean Won",
    symbolNative: "₩",
    decimalDigits: 0,
    rounding: 0,
    code: "KRW",
    namePlural: "South Korean won",
    typeId: 1,
  },
  {
    id: 80,
    symbol: "KD",
    name: "Kuwaiti Dinar",
    symbolNative: "د.ك.",
    decimalDigits: 3,
    rounding: 0,
    code: "KWD",
    namePlural: "Kuwaiti dinars",
    typeId: 1,
  },
  {
    id: 81,
    symbol: "CI$",
    name: "Cayman Islands Dollar",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "KYD",
    namePlural: "Cayman Islands Dollar",
    typeId: 1,
  },
  {
    id: 82,
    symbol: "KZT",
    name: "Kazakhstani Tenge",
    symbolNative: "тңг.",
    decimalDigits: 2,
    rounding: 0,
    code: "KZT",
    namePlural: "Kazakhstani tenges",
    typeId: 1,
  },
  {
    id: 83,
    symbol: "₭N",
    name: "Laotian Kip",
    symbolNative: "₭",
    decimalDigits: 0,
    rounding: 0,
    code: "LAK",
    namePlural: "Laotian Kip",
    typeId: 1,
  },
  {
    id: 84,
    symbol: "LB£",
    name: "Lebanese Pound",
    symbolNative: "ل.ل.",
    decimalDigits: 0,
    rounding: 0,
    code: "LBP",
    namePlural: "Lebanese pounds",
    typeId: 1,
  },
  {
    id: 85,
    symbol: "SLRs",
    name: "Sri Lankan Rupee",
    symbolNative: "SL Re",
    decimalDigits: 2,
    rounding: 0,
    code: "LKR",
    namePlural: "Sri Lankan rupees",
    typeId: 1,
  },
  {
    id: 86,
    symbol: "LD$",
    name: "Liberian Dollar",
    symbolNative: "L$",
    decimalDigits: 2,
    rounding: 0,
    code: "LRD",
    namePlural: "Liberian Dollar",
    typeId: 1,
  },
  {
    id: 87,
    symbol: "L",
    name: "Lesotho Loti",
    symbolNative: "M",
    decimalDigits: 2,
    rounding: 0,
    code: "LSL",
    namePlural: "Lesotho Loti",
    typeId: 1,
  },
  {
    id: 88,
    symbol: "Lt",
    name: "Lithuanian Litas",
    symbolNative: "Lt",
    decimalDigits: 2,
    rounding: 0,
    code: "LTL",
    namePlural: "Lithuanian litai",
    typeId: 1,
  },
  {
    id: 89,
    symbol: "Ls",
    name: "Latvian Lats",
    symbolNative: "Ls",
    decimalDigits: 2,
    rounding: 0,
    code: "LVL",
    namePlural: "Latvian lati",
    typeId: 1,
  },
  {
    id: 90,
    symbol: "LD",
    name: "Libyan Dinar",
    symbolNative: "د.ل.",
    decimalDigits: 3,
    rounding: 0,
    code: "LYD",
    namePlural: "Libyan dinars",
    typeId: 1,
  },
  {
    id: 91,
    symbol: "MAD",
    name: "Moroccan Dirham",
    symbolNative: "د.م.",
    decimalDigits: 2,
    rounding: 0,
    code: "MAD",
    namePlural: "Moroccan dirhams",
    typeId: 1,
  },
  {
    id: 92,
    symbol: "MDL",
    name: "Moldovan Leu",
    symbolNative: "MDL",
    decimalDigits: 2,
    rounding: 0,
    code: "MDL",
    namePlural: "Moldovan lei",
    typeId: 1,
  },
  {
    id: 93,
    symbol: "MGA",
    name: "Malagasy Ariary",
    symbolNative: "MGA",
    decimalDigits: 0,
    rounding: 0,
    code: "MGA",
    namePlural: "Malagasy Ariaries",
    typeId: 1,
  },
  {
    id: 94,
    symbol: "MKD",
    name: "Macedonian Denar",
    symbolNative: "MKD",
    decimalDigits: 2,
    rounding: 0,
    code: "MKD",
    namePlural: "Macedonian denari",
    typeId: 1,
  },
  {
    id: 95,
    symbol: "MMK",
    name: "Myanma Kyat",
    symbolNative: "K",
    decimalDigits: 0,
    rounding: 0,
    code: "MMK",
    namePlural: "Myanma kyats",
    typeId: 1,
  },
  {
    id: 96,
    symbol: "₮",
    name: "Mongolian Tugrik",
    symbolNative: "₮",
    decimalDigits: 2,
    rounding: 0,
    code: "MNT",
    namePlural: "Mongolian Tugrik",
    typeId: 1,
  },
  {
    id: 97,
    symbol: "MOP$",
    name: "Macanese Pataca",
    symbolNative: "MOP$",
    decimalDigits: 2,
    rounding: 0,
    code: "MOP",
    namePlural: "Macanese patacas",
    typeId: 1,
  },
  {
    id: 98,
    symbol: "UM",
    name: "Mauritanian ouguiya",
    symbolNative: "UM",
    decimalDigits: 2,
    rounding: 0,
    code: "MRO",
    namePlural: "Mauritanian ouguiyas",
    typeId: 1,
  },
  {
    id: 99,
    symbol: "MURs",
    name: "Mauritian Rupee",
    symbolNative: "MURs",
    decimalDigits: 0,
    rounding: 0,
    code: "MUR",
    namePlural: "Mauritian rupees",
    typeId: 1,
  },
  {
    id: 100,
    symbol: "MRf",
    name: "Maldivian Rufiyaa",
    symbolNative: "Rf",
    decimalDigits: 2,
    rounding: 0,
    code: "MVR",
    namePlural: "Maldivian Rufiyaa",
    typeId: 1,
  },
  {
    id: 101,
    symbol: "MK",
    name: "Malawian Kwacha",
    symbolNative: "MK",
    decimalDigits: 2,
    rounding: 0,
    code: "MWK",
    namePlural: "Malawian Kwacha",
    typeId: 1,
  },
  {
    id: 102,
    symbol: "MX$",
    name: "Mexican Peso",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "MXN",
    namePlural: "Mexican pesos",
    typeId: 1,
  },
  {
    id: 103,
    symbol: "RM",
    name: "Malaysian Ringgit",
    symbolNative: "RM",
    decimalDigits: 2,
    rounding: 0,
    code: "MYR",
    namePlural: "Malaysian ringgits",
    typeId: 1,
  },
  {
    id: 104,
    symbol: "MTn",
    name: "Mozambican Metical",
    symbolNative: "MTn",
    decimalDigits: 2,
    rounding: 0,
    code: "MZN",
    namePlural: "Mozambican meticals",
    typeId: 1,
  },
  {
    id: 105,
    symbol: "N$",
    name: "Namibian Dollar",
    symbolNative: "N$",
    decimalDigits: 2,
    rounding: 0,
    code: "NAD",
    namePlural: "Namibian dollars",
    typeId: 1,
  },
  {
    id: 106,
    symbol: "₦",
    name: "Nigerian Naira",
    symbolNative: "₦",
    decimalDigits: 2,
    rounding: 0,
    code: "NGN",
    namePlural: "Nigerian nairas",
    typeId: 1,
  },
  {
    id: 107,
    symbol: "C$",
    name: "Nicaraguan Córdoba",
    symbolNative: "C$",
    decimalDigits: 2,
    rounding: 0,
    code: "NIO",
    namePlural: "Nicaraguan córdobas",
    typeId: 1,
  },
  {
    id: 108,
    symbol: "Nkr",
    name: "Norwegian Krone",
    symbolNative: "kr",
    decimalDigits: 2,
    rounding: 0,
    code: "NOK",
    namePlural: "Norwegian kroner",
    typeId: 1,
  },
  {
    id: 109,
    symbol: "NPRs",
    name: "Nepalese Rupee",
    symbolNative: "नेरू",
    decimalDigits: 2,
    rounding: 0,
    code: "NPR",
    namePlural: "Nepalese rupees",
    typeId: 1,
  },
  {
    id: 110,
    symbol: "NZ$",
    name: "New Zealand Dollar",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "NZD",
    namePlural: "New Zealand dollars",
    typeId: 1,
  },
  {
    id: 111,
    symbol: "OMR",
    name: "Omani Rial",
    symbolNative: "ر.ع.",
    decimalDigits: 3,
    rounding: 0,
    code: "OMR",
    namePlural: "Omani rials",
    typeId: 1,
  },
  {
    id: 112,
    symbol: "B/.",
    name: "Panamanian Balboa",
    symbolNative: "B/.",
    decimalDigits: 2,
    rounding: 0,
    code: "PAB",
    namePlural: "Panamanian balboas",
    typeId: 1,
  },
  {
    id: 113,
    symbol: "S/.",
    name: "Peruvian Nuevo Sol",
    symbolNative: "S/.",
    decimalDigits: 2,
    rounding: 0,
    code: "PEN",
    namePlural: "Peruvian nuevos soles",
    typeId: 1,
  },
  {
    id: 114,
    symbol: "K",
    name: "Papua New Guinean Kina",
    symbolNative: "K",
    decimalDigits: 2,
    rounding: 0,
    code: "PGK",
    namePlural: "Papua New Guinean Kina",
    typeId: 1,
  },
  {
    id: 115,
    symbol: "₱",
    name: "Philippine Peso",
    symbolNative: "₱",
    decimalDigits: 2,
    rounding: 0,
    code: "PHP",
    namePlural: "Philippine pesos",
    typeId: 1,
  },
  {
    id: 116,
    symbol: "PKRs",
    name: "Pakistani Rupee",
    symbolNative: "₨",
    decimalDigits: 0,
    rounding: 0,
    code: "PKR",
    namePlural: "Pakistani rupees",
    typeId: 1,
  },
  {
    id: 117,
    symbol: "zł",
    name: "Polish Zloty",
    symbolNative: "zł",
    decimalDigits: 2,
    rounding: 0,
    code: "PLN",
    namePlural: "Polish zlotys",
    typeId: 1,
  },
  {
    id: 118,
    symbol: "₲",
    name: "Paraguayan Guarani",
    symbolNative: "₲",
    decimalDigits: 0,
    rounding: 0,
    code: "PYG",
    namePlural: "Paraguayan guaranis",
    typeId: 1,
  },
  {
    id: 119,
    symbol: "QR",
    name: "Qatari Rial",
    symbolNative: "ر.ق.",
    decimalDigits: 2,
    rounding: 0,
    code: "QAR",
    namePlural: "Qatari rials",
    typeId: 1,
  },
  {
    id: 120,
    symbol: "RON",
    name: "Romanian Leu",
    symbolNative: "RON",
    decimalDigits: 2,
    rounding: 0,
    code: "RON",
    namePlural: "Romanian lei",
    typeId: 1,
  },
  {
    id: 121,
    symbol: "din.",
    name: "Serbian Dinar",
    symbolNative: "дин.",
    decimalDigits: 0,
    rounding: 0,
    code: "RSD",
    namePlural: "Serbian dinars",
    typeId: 1,
  },
  {
    id: 122,
    symbol: "RUB",
    name: "Russian Ruble",
    symbolNative: "руб.",
    decimalDigits: 2,
    rounding: 0,
    code: "RUB",
    namePlural: "Russian rubles",
    typeId: 1,
  },
  {
    id: 123,
    symbol: "RWF",
    name: "Rwandan Franc",
    symbolNative: "FR",
    decimalDigits: 0,
    rounding: 0,
    code: "RWF",
    namePlural: "Rwandan francs",
    typeId: 1,
  },
  {
    id: 124,
    symbol: "SR",
    name: "Saudi Riyal",
    symbolNative: "ر.س.",
    decimalDigits: 2,
    rounding: 0,
    code: "SAR",
    namePlural: "Saudi riyals",
    typeId: 1,
  },
  {
    id: 125,
    symbol: "SI$",
    name: "Solomon Islands Dollar",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "SBD",
    namePlural: "Solomon Islands Dollars",
    typeId: 1,
  },
  {
    id: 126,
    symbol: "SRe",
    name: "Seychellois Rupee",
    symbolNative: "SR",
    decimalDigits: 2,
    rounding: 0,
    code: "SCR",
    namePlural: "Seychellois Rupees",
    typeId: 1,
  },
  {
    id: 127,
    symbol: "SDG",
    name: "Sudanese Pound",
    symbolNative: "SDG",
    decimalDigits: 2,
    rounding: 0,
    code: "SDG",
    namePlural: "Sudanese pounds",
    typeId: 1,
  },
  {
    id: 128,
    symbol: "Skr",
    name: "Swedish Krona",
    symbolNative: "kr",
    decimalDigits: 2,
    rounding: 0,
    code: "SEK",
    namePlural: "Swedish kronor",
    typeId: 1,
  },
  {
    id: 129,
    symbol: "S$",
    name: "Singapore Dollar",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "SGD",
    namePlural: "Singapore dollars",
    typeId: 1,
  },
  {
    id: 130,
    symbol: "£",
    name: "Saint Helena Pound",
    symbolNative: "£",
    decimalDigits: 2,
    rounding: 0,
    code: "SHP",
    namePlural: "Saint Helena Pounds",
    typeId: 1,
  },
  {
    id: 131,
    symbol: "Le",
    name: "Sierra Leonean Leone",
    symbolNative: "Le",
    decimalDigits: 2,
    rounding: 0,
    code: "SLL",
    namePlural: "Sierra Leonean Leone",
    typeId: 1,
  },
  {
    id: 132,
    symbol: "Ssh",
    name: "Somali Shilling",
    symbolNative: "Ssh",
    decimalDigits: 0,
    rounding: 0,
    code: "SOS",
    namePlural: "Somali shillings",
    typeId: 1,
  },
  {
    id: 133,
    symbol: "$",
    name: "Surinamese Dollar",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "SRD",
    namePlural: "Surinamese Dollar",
    typeId: 1,
  },
  {
    id: 134,
    symbol: "Db",
    name: "São Tomé and Príncipe dobra",
    symbolNative: "Db",
    decimalDigits: 2,
    rounding: 0,
    code: "STD",
    namePlural: "São Tomé and Príncipe dobras",
    typeId: 1,
  },
  {
    id: 135,
    symbol: "₡",
    name: "Salvadoran Colón",
    symbolNative: "₡",
    decimalDigits: 2,
    rounding: 0,
    code: "SVC",
    namePlural: "Salvadoran Colón",
    typeId: 1,
  },
  {
    id: 136,
    symbol: "SY£",
    name: "Syrian Pound",
    symbolNative: "ل.س.",
    decimalDigits: 0,
    rounding: 0,
    code: "SYP",
    namePlural: "Syrian pounds",
    typeId: 1,
  },
  {
    id: 137,
    symbol: "L",
    name: "Swazi Lilangeni",
    symbolNative: "E",
    decimalDigits: 2,
    rounding: 0,
    code: "SZL",
    namePlural: "Swazi Lilangeni",
    typeId: 1,
  },
  {
    id: 138,
    symbol: "฿",
    name: "Thai Baht",
    symbolNative: "฿",
    decimalDigits: 2,
    rounding: 0,
    code: "THB",
    namePlural: "Thai baht",
    typeId: 1,
  },
  {
    id: 139,
    symbol: "TJS",
    name: "Tajikistani Somoni",
    symbolNative: "TJS",
    decimalDigits: 2,
    rounding: 0,
    code: "TJS",
    namePlural: "Tajikistani Somoni",
    typeId: 1,
  },
  {
    id: 140,
    symbol: "T",
    name: "Turkmenistani Manat",
    symbolNative: "T",
    decimalDigits: 2,
    rounding: 0,
    code: "TMT",
    namePlural: "Turkmenistani Manat",
    typeId: 1,
  },
  {
    id: 141,
    symbol: "DT",
    name: "Tunisian Dinar",
    symbolNative: "د.ت.",
    decimalDigits: 3,
    rounding: 0,
    code: "TND",
    namePlural: "Tunisian dinars",
    typeId: 1,
  },
  {
    id: 142,
    symbol: "T$",
    name: "Tongan Paʻanga",
    symbolNative: "T$",
    decimalDigits: 2,
    rounding: 0,
    code: "TOP",
    namePlural: "Tongan paʻanga",
    typeId: 1,
  },
  {
    id: 143,
    symbol: "TL",
    name: "Turkish Lira",
    symbolNative: "TL",
    decimalDigits: 2,
    rounding: 0,
    code: "TRY",
    namePlural: "Turkish Lira",
    typeId: 1,
  },
  {
    id: 144,
    symbol: "TT$",
    name: "Trinidad and Tobago Dollar",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "TTD",
    namePlural: "Trinidad and Tobago dollars",
    typeId: 1,
  },
  {
    id: 145,
    symbol: "NT$",
    name: "New Taiwan Dollar",
    symbolNative: "NT$",
    decimalDigits: 2,
    rounding: 0,
    code: "TWD",
    namePlural: "New Taiwan dollars",
    typeId: 1,
  },
  {
    id: 146,
    symbol: "TSh",
    name: "Tanzanian Shilling",
    symbolNative: "TSh",
    decimalDigits: 0,
    rounding: 0,
    code: "TZS",
    namePlural: "Tanzanian shillings",
    typeId: 1,
  },
  {
    id: 147,
    symbol: "₴",
    name: "Ukrainian Hryvnia",
    symbolNative: "₴",
    decimalDigits: 2,
    rounding: 0,
    code: "UAH",
    namePlural: "Ukrainian hryvnias",
    typeId: 1,
  },
  {
    id: 148,
    symbol: "USh",
    name: "Ugandan Shilling",
    symbolNative: "USh",
    decimalDigits: 0,
    rounding: 0,
    code: "UGX",
    namePlural: "Ugandan shillings",
    typeId: 1,
  },
  {
    id: 149,
    symbol: "$",
    name: "US Dollar",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "USD",
    namePlural: "US dollars",
    typeId: 1,
  },
  {
    id: 150,
    symbol: "$U",
    name: "Uruguayan Peso",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "UYU",
    namePlural: "Uruguayan pesos",
    typeId: 1,
  },
  {
    id: 151,
    symbol: "UZS",
    name: "Uzbekistan Som",
    symbolNative: "UZS",
    decimalDigits: 0,
    rounding: 0,
    code: "UZS",
    namePlural: "Uzbekistan som",
    typeId: 1,
  },
  {
    id: 152,
    symbol: "Bs.F.",
    name: "Venezuelan Bolívar",
    symbolNative: "Bs.F.",
    decimalDigits: 2,
    rounding: 0,
    code: "VEF",
    namePlural: "Venezuelan bolívars",
    typeId: 1,
  },
  {
    id: 153,
    symbol: "₫",
    name: "Vietnamese Dong",
    symbolNative: "₫",
    decimalDigits: 0,
    rounding: 0,
    code: "VND",
    namePlural: "Vietnamese dong",
    typeId: 1,
  },
  {
    id: 154,
    symbol: "VUV",
    name: "Vanuatu Vatu",
    symbolNative: "VT",
    decimalDigits: 0,
    rounding: 0,
    code: "VUV",
    namePlural: "Vanuatu Vatu",
    typeId: 1,
  },
  {
    id: 155,
    symbol: "WS$",
    name: "Samoan Tala",
    symbolNative: "T",
    decimalDigits: 2,
    rounding: 0,
    code: "WST",
    namePlural: "Samoan Tala",
    typeId: 1,
  },
  {
    id: 156,
    symbol: "FCFA",
    name: "CFA Franc BEAC",
    symbolNative: "FCFA",
    decimalDigits: 0,
    rounding: 0,
    code: "XAF",
    namePlural: "CFA francs BEAC",
    typeId: 1,
  },
  {
    id: 157,
    symbol: "XAG",
    name: "Silver Ounce",
    symbolNative: "XAG",
    decimalDigits: 2,
    rounding: 0,
    code: "XAG",
    namePlural: "Silver Ounces",
    typeId: 3,
  },
  {
    id: 158,
    symbol: "XAU",
    name: "Gold Ounce",
    symbolNative: "XAU",
    decimalDigits: 2,
    rounding: 0,
    code: "XAU",
    namePlural: "Gold Ounces",
    typeId: 3,
  },
  {
    id: 159,
    symbol: "EC$",
    name: "East Caribbean Dollar",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "XCD",
    namePlural: "East Caribbean Dollars",
    typeId: 1,
  },
  {
    id: 160,
    symbol: "SDR",
    name: "Special drawing rights",
    symbolNative: "SDR",
    decimalDigits: 2,
    rounding: 0,
    code: "XDR",
    namePlural: "Special drawing rights",
    typeId: 1,
  },
  {
    id: 161,
    symbol: "CFA",
    name: "CFA Franc BCEAO",
    symbolNative: "CFA",
    decimalDigits: 0,
    rounding: 0,
    code: "XOF",
    namePlural: "CFA francs BCEAO",
    typeId: 1,
  },
  {
    id: 162,
    symbol: "CFP",
    name: "CFP Franc",
    symbolNative: "CFP",
    decimalDigits: 0,
    rounding: 0,
    code: "XPF",
    namePlural: "CFP francs",
    typeId: 1,
  },
  {
    id: 163,
    symbol: "YR",
    name: "Yemeni Rial",
    symbolNative: "ر.ي.",
    decimalDigits: 0,
    rounding: 0,
    code: "YER",
    namePlural: "Yemeni rials",
    typeId: 1,
  },
  {
    id: 164,
    symbol: "R",
    name: "South African Rand",
    symbolNative: "R",
    decimalDigits: 2,
    rounding: 0,
    code: "ZAR",
    namePlural: "South African rand",
    typeId: 1,
  },
  {
    id: 165,
    symbol: "ZK",
    name: "Zambian Kwacha",
    symbolNative: "ZK",
    decimalDigits: 0,
    rounding: 0,
    code: "ZMK",
    namePlural: "Zambian kwachas",
    typeId: 1,
  },
  {
    id: 166,
    symbol: "ZK",
    name: "Zambian Kwacha",
    symbolNative: "ZK",
    decimalDigits: 0,
    rounding: 0,
    code: "ZMW",
    namePlural: "Zambian kwachas",
    typeId: 1,
  },
  {
    id: 167,
    symbol: "ZWL",
    name: "Zimbabwean dollar",
    symbolNative: "$",
    decimalDigits: 2,
    rounding: 0,
    code: "ZWL",
    namePlural: "Zimbabwean dollars",
    typeId: 1,
  },
  {
    id: 168,
    symbol: "XPT",
    name: "Platinum Ounce",
    symbolNative: "XPT",
    decimalDigits: 6,
    rounding: 0,
    code: "XPT",
    namePlural: "Platinum Ounces",
    typeId: 3,
  },
  {
    id: 169,
    symbol: "XPD",
    name: "Palladium Ounce",
    symbolNative: "XPD",
    decimalDigits: 6,
    rounding: 0,
    code: "XPD",
    namePlural: "Palladium Ounces",
    typeId: 3,
  },
  {
    id: 170,
    symbol: "₿",
    name: "Bitcoin",
    symbolNative: "₿",
    decimalDigits: 8,
    rounding: 0,
    code: "BTC",
    namePlural: "Bitcoins",
    typeId: 2,
  },
  {
    id: 171,
    symbol: "Ξ",
    name: "Ethereum",
    symbolNative: "Ξ",
    decimalDigits: 18,
    rounding: 0,
    code: "ETH",
    namePlural: "Ethereum",
    typeId: 2,
  },
  {
    id: 172,
    symbol: "BNB",
    name: "Binance",
    symbolNative: "BNB",
    decimalDigits: 8,
    rounding: 0,
    code: "BNB",
    namePlural: "Binance",
    typeId: 2,
  },
  {
    id: 173,
    symbol: "XRP",
    name: "Ripple",
    symbolNative: "XRP",
    decimalDigits: 6,
    rounding: 0,
    code: "XRP",
    namePlural: "Ripple",
    typeId: 2,
  },
  {
    id: 174,
    symbol: "SOL",
    name: "Solana",
    symbolNative: "SOL",
    decimalDigits: 9,
    rounding: 0,
    code: "SOL",
    namePlural: "Solana",
    typeId: 2,
  },
  {
    id: 175,
    symbol: "DOT",
    name: "Polkadot",
    symbolNative: "DOT",
    decimalDigits: 10,
    rounding: 0,
    code: "DOT",
    namePlural: "Polkadot",
    typeId: 2,
  },
  {
    id: 176,
    symbol: "AVAX",
    name: "Avalanche",
    symbolNative: "AVAX",
    decimalDigits: 18,
    rounding: 0,
    code: "AVAX",
    namePlural: "Avalanche",
    typeId: 2,
  },
  {
    id: 177,
    symbol: "MATIC",
    name: "Matic Token",
    symbolNative: "MATIC",
    decimalDigits: 18,
    rounding: 0,
    code: "MATIC",
    namePlural: "Matic Tokens",
    typeId: 2,
  },
  {
    id: 178,
    symbol: "Ł",
    name: "Litecoin",
    symbolNative: "Ł",
    decimalDigits: 8,
    rounding: 0,
    code: "LTC",
    namePlural: "Litecoins",
    typeId: 2,
  },
  {
    id: 179,
    symbol: "ADA",
    name: "Cardano",
    symbolNative: "ADA",
    decimalDigits: 6,
    rounding: 0,
    code: "ADA",
    namePlural: "Cardanos",
    typeId: 2,
  },
  {
    id: 180,
    symbol: "USDT",
    name: "Tether",
    symbolNative: "USDT",
    decimalDigits: 2,
    rounding: 0,
    code: "USDT",
    namePlural: "Tethers",
    typeId: 2,
  },
  {
    id: 181,
    symbol: "USDC",
    name: "USD Coin",
    symbolNative: "USDC",
    decimalDigits: 2,
    rounding: 0,
    code: "USDC",
    namePlural: "USD Coins",
    typeId: 2,
  },
  {
    id: 182,
    symbol: "DAI",
    name: "Dai",
    symbolNative: "DAI",
    decimalDigits: 2,
    rounding: 0,
    code: "DAI",
    namePlural: "Dais",
    typeId: 2,
  },
  {
    id: 183,
    symbol: "ARB",
    name: "Arbitrum",
    symbolNative: "ARB",
    decimalDigits: 8,
    rounding: 0,
    code: "ARB",
    namePlural: "Arbitrums",
    typeId: 2,
  },
  {
    id: 184,
    symbol: "OP",
    name: "Optimism",
    symbolNative: "OP",
    decimalDigits: 8,
    rounding: 0,
    code: "OP",
    namePlural: "Optimism",
    typeId: 2,
  },
  {
    id: 185,
    symbol: "Bs.S.",
    name: "Venezuelan Bolívar",
    symbolNative: "Bs.S.",
    decimalDigits: 2,
    rounding: 0,
    code: "VES",
    namePlural: "Venezuelan bolívars",
    typeId: 1,
  },
  {
    id: 186,
    symbol: "STN",
    name: "São Tomé and Príncipe dobra",
    symbolNative: "STN",
    decimalDigits: 2,
    rounding: 0,
    code: "STN",
    namePlural: "dobra",
    typeId: 1,
  },
  {
    id: 187,
    symbol: "MRU",
    name: "Mauritanian ouguiya",
    symbolNative: "MRU",
    decimalDigits: 2,
    rounding: 0,
    code: "MRU",
    namePlural: "ouguiya",
    typeId: 1,
  },
  {
    id: 188,
    symbol: "ZWG",
    name: "Zimbabwe Gold",
    symbolNative: "ZWG",
    decimalDigits: 2,
    rounding: 0,
    code: "ZWG",
    namePlural: "Zimbabwean gold",
    typeId: 1,
  },
  {
    id: 189,
    symbol: "SLE",
    name: "Sierra Leonean leone",
    symbolNative: "SLE",
    decimalDigits: 2,
    rounding: 0,
    code: "SLE",
    namePlural: "leone",
    typeId: 1,
  },
];

const insertCurrencyType = async () => {
  await db
    .createQueryBuilder()
    .insert()
    .into(CurrencyType)
    .values(currencyTypes)
    .orUpdate(["name"], ["id"], { skipUpdateIfNoValuesChanged: true })
    .execute();
};

const insertCurrencies = async () => {
  await db
    .createQueryBuilder()
    .insert()
    .into(Currency)
    .values(currencies)
    .orUpdate(
      [
        "name",
        "namePlural",
        "typeId",
        "code",
        "symbol",
        "symbolNative",
        "decimalDigits",
      ],
      ["id"],
      {
        skipUpdateIfNoValuesChanged: true,
      }
    )
    .execute();
};

export { insertCurrencyType, insertCurrencies };
